services:
  bot:
    build: .
    container_name: innervoice-bot
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      - mysql
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py

  mysql:
    image: mysql:8.0
    container_name: innervoice-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf:ro

    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  mysql_data:
